### ISSUE TITLE
composer.lock file not in sync with composer.json

### ISSUE THREAD

**Issue by agemmell** [numerogeek/ultimate-symfony2-boilerplate#3]
After cloning I ran composer install and got this warning.
Not exactly hard to fix - I just ran composer update afterwards! - but I thought I'd let you know in case you wanted to get them in sync :)

**Comment by numerogeek** [comment]
Thank @agemmell for pointing that out  :)
fixed. e89135e900184ed344a5d370a1e226eb67bff96f

Otherwise, what do you think of this boilerplate ? Does it miss something ?

**Comment by agemmell** [comment]
I haven't had a chance to play with it too deeply but I got it all setup pretty easily - even when exhausted late last night!  

I wasn't expecting it to all be in French so that was a little surprise, or should I say "une surprise" :)  I know where to change the locale so it was easy for me to flip to English - so thank you for including English translation files because I wasn't looking forward to translating what was already there!

I didn't notice the Bower requirement until I was working through your step-by-step instructions, so maybe make that a little clearer?  

After trying to run "php app/console avanzu:admin:fetch-vendor" it gave me an error that it couldn't find node.  I've seen this error before.  It's because the node binary gets installed as nodejs so I just symlinked /usr/bin/nodejs to /usr/bin/node and ran the command again and it worked.  That's a bit outside the scope of your project but you may want to add a little note for future users.

I will actually be diving in and trying to manipulate it to my needs in the coming weeks and months.  So far so good!  Thank you!

**Comment by numerogeek** [comment]
Thank you for your feedback :)
I am going to release a Vagrant file with everything included :) ( nginx
php mysql nodejs composer bower etc ... )

On Fri, Sep 18, 2015 at 6:06 PM, Alex Gemmell notifications@github.com
wrote:

> I haven't had a chance to play with it too deeply but I got it all setup
> pretty easily - even when exhausted late last night!
> 
> I wasn't expecting it to all be in French so that was a little surprise,
> or should I say "une surprise" :) I know where to change the locale so it
> was easy for me to flip to English - so thank you for including English
> translation files because I wasn't looking forward to translating what was
> already there!
> 
> I didn't notice the Bower requirement until I was working through your
> step-by-step instructions, so maybe make that a little clearer?
> 
> After trying to run "php app/console avanzu:admin:fetch-vendor" it gave me
> an error that it couldn't find node. I've seen this error before. It's
> because the node binary gets installed as nodejs so I just symlinked
> /usr/bin/nodejs to /usr/bin/node and ran the command again and it worked.
> That's a bit outside the scope of your project but you may want to add a
> little note for future users.
> 
> I will actually be diving in and trying to manipulate it to my needs in
> the coming weeks and months. So far so good! Thank you!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/numerogeek/ultimate-symfony2-boilerplate/issues/3#issuecomment-141494609
> .

## 

Geoffrey Monté
